#!/bin/bash
# Generate tool integrations into nushell's vendor/autoload/, which nushell
# sources automatically. Re-runs when this script's hash changes — `touch` it
# and re-apply to refresh after upgrading a tool.
#
# Every generator soft-fails on a missing tool so a fresh machine (where the
# Brewfile run hasn't finished) doesn't break the whole apply chain; the
# script re-runs on the next apply since its hash is unchanged.

set -euo pipefail

VENDOR_AUTOLOAD="$HOME/.config/nushell/vendor/autoload"
mkdir -p "$VENDOR_AUTOLOAD"

if command -v starship >/dev/null 2>&1; then
    starship init nu > "$VENDOR_AUTOLOAD/starship.nu"
    echo "Generated $VENDOR_AUTOLOAD/starship.nu"
else
    echo "WARN: starship not found; skipping starship.nu"
fi

if command -v zoxide >/dev/null 2>&1; then
    zoxide init nushell > "$VENDOR_AUTOLOAD/zoxide.nu"
    echo "Generated $VENDOR_AUTOLOAD/zoxide.nu"
else
    echo "WARN: zoxide not found; skipping zoxide.nu"
fi

if command -v carapace >/dev/null 2>&1; then
    carapace _carapace nushell > "$VENDOR_AUTOLOAD/carapace.nu"
    echo "Generated $VENDOR_AUTOLOAD/carapace.nu"
else
    echo "WARN: carapace not found; skipping carapace.nu"
fi

if command -v atuin >/dev/null 2>&1; then
    # `--disable-up-arrow` keeps Up as nushell's in-line history; only Ctrl+R
    # goes to atuin's full-screen TUI.
    atuin init nu --disable-up-arrow > "$VENDOR_AUTOLOAD/atuin.nu"

    # Patch (verified still needed at nushell 0.114 + atuin 18.19): upstream ships a multi-line `cmd:` string in the
    # Ctrl+R keybinding, which reedline injects back into the buffer after the
    # TUI returns. Collapsing `cmd` to a single identifier sidesteps that; the
    # pre_execution override then keeps the wrapper out of atuin's history.
    cat >> "$VENDOR_AUTOLOAD/atuin.nu" <<'NU_EOF'

# --- dotfiles patch: avoid multi-line executehostcommand cmd ---
# Reedline renders an `executehostcommand` cmd string back into the terminal
# both before and after the TUI runs, hence the two ANSI scrubs.
def _atuin_search_exec [] {
    let q = (commandline)
    print -n $"(ansi --escape '2K')\r"
    with-env { ATUIN_LOG: error, ATUIN_QUERY: $q, ATUIN_SHELL: nu } {
        let output = (run-external atuin search "--interactive" e>| str trim)
        if ($output | str starts-with "__atuin_accept__:") {
            commandline edit --accept ($output | str replace "__atuin_accept__:" "")
        } else {
            commandline edit --replace $output
        }
    }
    print -n $"(ansi --escape '2K')\r"
}

# Replace atuin's pre_execution hook with one that also ignores our wrapper.
let _atuin_pre_execution_patched = {||
    if ($nu | get history-enabled?) == false {
        return
    }
    let cmd = (commandline)
    if ($cmd | is-empty) {
        return
    }
    if ($cmd | str trim) == "_atuin_search_exec" {
        return
    }
    if not ($cmd | str starts-with $ATUIN_KEYBINDING_TOKEN) {
        $env.ATUIN_HISTORY_ID = (atuin history start -- $cmd | complete | get stdout | str trim)
    }
}

$env.config = (
    $env.config | upsert hooks.pre_execution (
        $env.config.hooks.pre_execution
        | where {|h| $h != $_atuin_pre_execution }
        | append $_atuin_pre_execution_patched
    ) | upsert keybindings (
        $env.config.keybindings
        | where name != atuin
        | append {
            name: atuin
            modifier: control
            keycode: char_r
            mode: [emacs, vi_normal, vi_insert]
            event: { send: executehostcommand cmd: "_atuin_search_exec" }
        }
    )
)
NU_EOF

    echo "Generated $VENDOR_AUTOLOAD/atuin.nu (with multiline-cmd workaround)"
else
    echo "WARN: atuin not found; skipping atuin.nu"
fi

# --- nushell plugins ---
# `plugin use` lines live here, NOT in config.nu. `plugin use` is a PARSER
# KEYWORD: a missing registry aborts the entire config with "Plugin registry
# file can't be opened", leaving every new shell broken — including the one
# you'd fix it from. An `if` guard in config.nu does not help; it runs after
# parsing already failed. So gate on the registry existing, and emit only the
# plugins actually built, so one failed build costs a feature not the shell.
#
# Names come from the cargo binaries, not `plugin list` — the latter reports
# plugins loaded in the CURRENT scope, which needs the very config being
# generated here.
PLUGIN_FILE="$VENDOR_AUTOLOAD/plugins.nu"
PLUGIN_BIN_DIR="$HOME/.cargo/bin"
if [ -f "$HOME/.config/nushell/plugin.msgpackz" ] && \
   ls "$PLUGIN_BIN_DIR"/nu_plugin_* >/dev/null 2>&1; then
    {
        echo "# Generated by run_onchange_after_02-generate-nushell-integrations.sh"
        echo "# Do not edit — re-run the generator after \`plugin add\`."
        for bin in "$PLUGIN_BIN_DIR"/nu_plugin_*; do
            echo "plugin use $(basename "$bin" | sed 's/^nu_plugin_//')"
        done
    } > "$PLUGIN_FILE"
    echo "Generated $PLUGIN_FILE"
else
    # Remove a stale file: `plugin use` of an unregistered plugin also fails
    # at parse time.
    rm -f "$PLUGIN_FILE"
    echo "WARN: no plugin registry; skipping plugins.nu (run 'make bootstrap-plugins')"
fi

# direnv is absent here on purpose: it has no `direnv hook nu`. Its bridge is
# a hand-written module at dot_config/nushell/autoload/direnv.nu.
